package gui;

import bo.LoginBO;
import dao.LoginDAO;
import entity.Login;
import entity.Login;
import exception.NegocioException;
import exception.ValidacaoException;
import static gui.LoginFrame.id;
import static gui.LoginFrame.login;
import static gui.LoginFrame.nivel;
import static gui.LoginFrame.senha;
import static gui.LoginFrame.url;
import static gui.LoginFrame.utilizador;
import util.MensagensUtil;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class UtilizadoresFrame extends javax.swing.JFrame {

    private File caminho;
    private BufferedImage image;
    private String caminhoUrl;
    private Long idLogin;

    public UtilizadoresFrame() {
        initComponents();

        txtLogin.setText(login);
        txtSenha.setText(senha);
        txtNome.setText(utilizador);
        comboNivel.setSelectedItem(nivel);

        btnGuardar.setText("Actualizar");

        idLogin = id;
        caminhoUrl = url;

        try {
            if (url == null || url.equals("")) {
                image = null;
            } else {
            image = ImageIO.read(new File(url));
            ImageIcon img = new ImageIcon(image);
            lblAssinatura.setIcon(img);
            }
        } catch (IOException ex) {
            MensagensUtil.addMsg(UtilizadoresFrame.this, ex.getMessage());
        }

        if ("3".equals(nivel)) {
            getTableUtilizador();
            comboNivel.setEnabled(true);
            btnLimpar.setEnabled(true);
        }
    }

    private void limpar() {
        caminho = null;
        image = null;
        caminhoUrl = null;

        txtLogin.setText("");
        txtNome.setText("");
        txtSenha.setText("");

        lblAssinatura.setIcon(null);

        comboNivel.setSelectedIndex(-1);

        btnGuardar.setText("Guardar");
        btnExcluir.setEnabled(false);

        txtNome.requestFocus();

        idLogin = null;
    }

    private JTable getTableUtilizador() {

        if (tableUtilizadores == null) {
            tableUtilizadores = new JTable();
        } else {
            try {
                String[][] lista = new LoginBO().listagem();
                TableModel tableListConsultaModel
                        = new DefaultTableModel(
                                lista,
                                new String[]{"Utilizador", "Nivel", "Login"});
                tableUtilizadores.setModel(tableListConsultaModel);
                tableUtilizadores.getColumnModel().getColumn(0).setPreferredWidth(100);
                tableUtilizadores.getColumnModel().getColumn(1).setPreferredWidth(10);
                tableUtilizadores.getColumnModel().getColumn(2).setPreferredWidth(100);
            } catch (NegocioException e) {
                MensagensUtil.addMsg(UtilizadoresFrame.this, e.getMessage());
            }
        }
        return tableUtilizadores;
    }

    private static BufferedImage resize(BufferedImage img, int height, int width) {
        Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return resized;
    }

    public File selecionarImagem() {

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagem", "jpg", "png");
        fileChooser.addChoosableFileFilter(filtro);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogType(JFileChooser.OPEN_DIALOG);
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.showOpenDialog(this);

        return fileChooser.getSelectedFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblAssinatura = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboNivel = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUtilizadores = new javax.swing.JTable();
        btnAddSignature = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Utilizadores");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nome:");

        txtNome.setToolTipText("Digite apenas o primeiro e ultimo nome.");

        lblAssinatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAssinatura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assinatura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        lblAssinatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAssinatura.setMaximumSize(new java.awt.Dimension(140, 300));
        lblAssinatura.setMinimumSize(new java.awt.Dimension(140, 300));
        lblAssinatura.setPreferredSize(new java.awt.Dimension(140, 300));

        jLabel2.setText("Nivel:");

        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        comboNivel.setEnabled(false);

        jLabel3.setText("Login:");

        jLabel4.setText("Senha:");

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jSeparator2.setMaximumSize(new java.awt.Dimension(508, 8));
        jSeparator2.setMinimumSize(new java.awt.Dimension(508, 8));
        jSeparator2.setPreferredSize(new java.awt.Dimension(508, 8));

        tableUtilizadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableUtilizadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableUtilizadoresMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableUtilizadores);

        btnAddSignature.setText("Adicionar Assinatura");
        btnAddSignature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSignatureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSenha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddSignature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddSignature, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir)
                            .addComponent(btnLimpar)
                            .addComponent(btnGuardar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(641, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        switch (JOptionPane.showConfirmDialog(null, "Pretende apagar o Utilizador: "
                + txtNome.getText() + "\n\n...Esta operação é irreversível..."
                + "\n\nEste passo pode comprometer o acesso aos orçamentos criados pelo utilizador.", "ATENÇÃO",
                JOptionPane.WARNING_MESSAGE)) {
            case 0:
                new LoginDAO().delete(idLogin);
                limpar();
                if ("3".equals(nivel)) {
                    getTableUtilizador();

                } else {
                    btnGuardar.setText("Actualizar");
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAddSignatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSignatureActionPerformed
        caminho = selecionarImagem();
        caminhoUrl = caminho.toString();
        try {
            image = ImageIO.read(caminho);
            try {
                int largura = image.getWidth();
                int altura = image.getHeight();
                int imgAltura = 120;
                int imgLargura = 280;
                if (largura > altura && largura > imgLargura) {
                    //x = w - (w - x);
                    imgAltura = altura * imgLargura / largura;
                } else if (altura > largura && altura > imgAltura) {
                    //y = h - (h - y);
                    imgLargura = largura * imgAltura / altura;
                } else {
                    imgAltura = altura;
                    imgLargura = largura;
                }

                BufferedImage resized = resize(image, imgAltura, imgLargura);
                image = resized;
                ImageIcon img = new ImageIcon(image);
                lblAssinatura.setIcon(img);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        } catch (HeadlessException | IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnAddSignatureActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
        if ("3".equals(nivel)) {
            getTableUtilizador();

        } else {
            btnGuardar.setText("Actualizar");
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tableUtilizadoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUtilizadoresMousePressed
        if (tableUtilizadores.getSelectedRow() != -1) {
            limpar();
            Login log = new Login();

            log = new LoginDAO().findByLogin(tableUtilizadores.getValueAt(tableUtilizadores.getSelectedRow(), 2).toString());
            txtNome.setText(log.getUtilizador());
            comboNivel.setSelectedItem(log.getNivel());
            txtLogin.setText(log.getNome());
            txtSenha.setText(log.getSenha());
            idLogin = log.getId();

            if (log.getUrlLogo() != null) {
                try {
                    //caminhoUrl = log.getUrlLogo();
                    image = ImageIO.read(new File(log.getUrlLogo()));
                    ImageIcon img = new ImageIcon(image);
                    lblAssinatura.setIcon(img);

                } catch (IOException ex) {
                    MensagensUtil.addMsg(UtilizadoresFrame.this, ex.getMessage());
                }
            }

            btnExcluir.setEnabled(true);
            btnGuardar.setText("Actualizar");
        }

    }//GEN-LAST:event_tableUtilizadoresMousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Login log = new Login();

        String utilizadores = txtNome.getText();
        log.setUtilizador(utilizadores);
        String logins = txtLogin.getText();
        log.setNome(logins);
        String senha = new String(txtSenha.getPassword());
        log.setSenha(senha);
        log.setNivel(comboNivel.getSelectedItem().toString());

        if (caminhoUrl != null) {
            try {
                caminhoUrl = logins + ".png";
                log.setUrlLogo(caminhoUrl);
                ImageIO.write(image, "PNG", new File(caminhoUrl));
            } catch (IOException ex) {
                MensagensUtil.addMsg(UtilizadoresFrame.this, ex.getMessage());
            }
        }

        if (!"Guardar".equals(btnGuardar.getText())) {
            try {
                log.setId(idLogin);
                new LoginBO().validaUtilizador(utilizadores, logins, senha);
                new LoginBO().update(log);
                if ("3".equals(nivel)) {
                    getTableUtilizador();

                } else {
                    btnGuardar.setText("Actualizar");
                }
                if (login.equals(logins)) {
                    utilizador = utilizadores;
                    url = caminhoUrl;
                    this.dispose();
                    UtilizadoresFrame u = new UtilizadoresFrame();
                    u.setVisible(true);
                }
                limpar();
            } catch (ValidacaoException | NegocioException ex) {
                MensagensUtil.addMsg(UtilizadoresFrame.this, ex.getMessage());
            }

        } else {
            try {
                new LoginBO().validaUtilizador(utilizadores, logins, senha);
                new LoginBO().addUtilizador(log);
                getTableUtilizador();
                limpar();
            } catch (ValidacaoException | NegocioException ex) {
                MensagensUtil.addMsg(UtilizadoresFrame.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilizadoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilizadoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilizadoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilizadoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilizadoresFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSignature;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAssinatura;
    private javax.swing.JTable tableUtilizadores;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
